### PR TITLE
Update translation.json

### PR DESCRIPTION
**Pull request by dzielus**

### CODE REVIEW

**Comment by v2px** [comment]
Looks good, thank you!

**Comment by KrisCurious** [comment]
Can I add some more translated lines?

**Comment by dzielus** [comment]
Yes, of course.

2015-08-06 13:16 GMT+02:00 Kris notifications@github.com:

> Can I add some more translated lines?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/NeXTHorizon/hz-locales/pull/1#issuecomment-128331214.

## 

Pozdrawiam
Damian Dzielendziak

**Comment by KrisCurious** [comment]
I've never done that before. Actually because of this I've signed up in GitHub. 
Now tested on my fork, updated succesfully (problem with commit without -a). 
Is this possible to modify  json file from this web interface?

**Pull request merged**
